from __future__ import annotations

from collections import defaultdict
from typing import Any, Protocol

from app.state import ChatMessage


class ChatHistoryStore(Protocol):
    def list(self, user_id: str) -> list[ChatMessage]: ...

    def window(self, user_id: str, size: int) -> list[ChatMessage]: ...

    def append_exchange(self, user_id: str, user_message: str, assistant_message: str) -> None: ...

    def clear(self, user_id: str) -> int: ...


class InMemoryChatHistoryStore:
    def __init__(self, *, max_messages: int = 50) -> None:
        self.max_messages = max_messages
        self._history: dict[str, list[ChatMessage]] = defaultdict(list)

    def list(self, user_id: str) -> list[ChatMessage]:
        return list(self._history.get(user_id, []))

    def window(self, user_id: str, size: int) -> list[ChatMessage]:
        return self.list(user_id)[-size:]

    def append_exchange(self, user_id: str, user_message: str, assistant_message: str) -> None:
        self._history[user_id].extend(
            [
                {"role": "user", "content": user_message},
                {"role": "assistant", "content": assistant_message},
            ]
        )
        if self.max_messages > 0:
            self._history[user_id] = self._history[user_id][-self.max_messages :]

    def clear(self, user_id: str) -> int:
        count = len(self._history.get(user_id, []))
        self._history[user_id].clear()
        return count


class PostgresChatHistoryStore:
    def __init__(self, *, database_url: str, max_messages: int = 50) -> None:
        self.database_url = database_url
        self.max_messages = max_messages
        self._ensure_schema()

    def _connect(self) -> Any:
        import psycopg

        return psycopg.connect(self.database_url)

    def _ensure_schema(self) -> None:
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS chat_messages (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id TEXT NOT NULL,
                        role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
                        content TEXT NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                    )
                    """
                )
                cur.execute(
                    """
                    CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id_id
                    ON chat_messages (user_id, id)
                    """
                )

    def list(self, user_id: str) -> list[ChatMessage]:
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT role, content
                    FROM chat_messages
                    WHERE user_id = %s
                    ORDER BY id
                    """,
                    (user_id,),
                )
                return [{"role": role, "content": content} for role, content in cur.fetchall()]

    def window(self, user_id: str, size: int) -> list[ChatMessage]:
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT role, content
                    FROM (
                        SELECT id, role, content
                        FROM chat_messages
                        WHERE user_id = %s
                        ORDER BY id DESC
                        LIMIT %s
                    ) recent
                    ORDER BY id
                    """,
                    (user_id, size),
                )
                return [{"role": role, "content": content} for role, content in cur.fetchall()]

    def append_exchange(self, user_id: str, user_message: str, assistant_message: str) -> None:
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.executemany(
                    """
                    INSERT INTO chat_messages (user_id, role, content)
                    VALUES (%s, %s, %s)
                    """,
                    [
                        (user_id, "user", user_message),
                        (user_id, "assistant", assistant_message),
                    ],
                )
                if self.max_messages > 0:
                    cur.execute(
                        """
                        DELETE FROM chat_messages
                        WHERE user_id = %s
                          AND id NOT IN (
                            SELECT id
                            FROM chat_messages
                            WHERE user_id = %s
                            ORDER BY id DESC
                            LIMIT %s
                          )
                        """,
                        (user_id, user_id, self.max_messages),
                    )

    def clear(self, user_id: str) -> int:
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute("DELETE FROM chat_messages WHERE user_id = %s", (user_id,))
                return cur.rowcount


def build_chat_history_store(*, backend: str, database_url: str, max_messages: int) -> ChatHistoryStore:
    normalized = backend.strip().lower()
    if normalized == "postgres":
        return PostgresChatHistoryStore(database_url=database_url, max_messages=max_messages)
    if normalized == "memory":
        return InMemoryChatHistoryStore(max_messages=max_messages)
    raise ValueError(f"Unsupported chat history backend: {backend}")